# Generated by Django 5.0 on 2024-01-01 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('tipo_empleado', models.CharField(max_length=20)),
                ('tipo_contrato', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(choices=[('FARIAS', 'FARIAS'), ('GGARCIA', 'GGARCIA'), ('WMARUDENA', 'WMARUDENA'), ('NANDALUZ', 'NANDALUZ')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='myapp.usuario')),
            ],
        ),
    ]
