# Generated by Django 5.0 on 2024-01-02 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sugerencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
