# Generated by Django 5.0 on 2024-01-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_sugerencia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qresponsable', models.CharField(choices=[('nomina', 'Nomina'), ('campo', 'Campo'), ('mcontreras', 'MCONTRERAS'), ('msolis', 'MSOLIS'), ('mpico', 'MPICO')], max_length=20)),
                ('Qcausa', models.CharField(choices=[('asistencia_tarde', 'Asistencia llegó tarde'), ('no_reportado', 'No fue reportado'), ('mal_reportado', 'Mal reportado'), ('p_sindicales_atrasados', 'P. sindicales atrasados'), ('descuentos_atrasados', 'Descuentos atrasados'), ('valores_descuento_erroneos', 'Valores de descuento erróneos'), ('descuentos_jubilados', 'Descuentos de jubilados')], max_length=30)),
                ('Qestado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta')], max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='myapp.usuario')),
            ],
        ),
    ]
