# Generated by Django 5.0 on 2024-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_queja_qfecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='Qresponsable',
            field=models.CharField(choices=[('Comunicacion_cultura', 'Comunicación clima y cultura'), ('Desarrollo_laboral', 'Desarrollo y relaciones laborales'), ('Nomina_compensaciones', 'Nomina y compensaciones'), ('Seguridad_salud_ambiente', 'Seguridad, salud y ambiente'), ('Servicios_generales', 'Servicios generales'), ('Campo', 'Campo'), ('Fabrica', 'Fabrica')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='responsable',
            field=models.CharField(choices=[('Comunicacion_cultura', 'Comunicación clima y cultura'), ('Desarrollo_laboral', 'Desarrollo y relaciones laborales'), ('Nomina_compensaciones', 'Nomina y compensaciones'), ('Seguridad_salud_ambiente', 'Seguridad, salud y ambiente'), ('Servicios_generales', 'Servicios generales'), ('Campo', 'Campo'), ('Fabrica', 'Fabrica')], max_length=50),
        ),
    ]
