# Generated by Django 5.0 on 2024-01-06 20:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_queja_qresponsable_alter_sugerencia_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pfecha', models.DateField(default=datetime.date.today)),
                ('Presponsable', models.CharField(choices=[('Comunicacion_cultura', 'Comunicación clima y cultura'), ('Desarrollo_laboral', 'Desarrollo y relaciones laborales'), ('Nomina_compensaciones', 'Nomina y compensaciones'), ('Seguridad_salud_ambiente', 'Seguridad, salud y ambiente'), ('Servicios_generales', 'Servicios generales')], max_length=50)),
                ('Pcausa', models.CharField(choices=[('actualizacion', 'Actualizar datos'), ('no_reportado', 'No fue reportado'), ('mal_reportado', 'Mal reportado'), ('p_sindicales_atrasados', 'P. sindicales atrasados'), ('descuentos_atrasados', 'Descuentos atrasados'), ('valores_descuento_erroneos', 'Valores de descuento erróneos'), ('descuentos_jubilados', 'Descuentos de jubilados')], max_length=30)),
                ('Pestado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peticion', to='myapp.usuario')),
            ],
        ),
    ]
