# Generated by Django 5.0 on 2024-01-06 22:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_peticion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rfecha', models.DateField(default=datetime.date.today)),
                ('Rresponsable', models.CharField(choices=[('Comunicacion_cultura', 'Comunicación clima y cultura'), ('Desarrollo_laboral', 'Desarrollo y relaciones laborales'), ('Nomina_compensaciones', 'Nomina y compensaciones'), ('Seguridad_salud_ambiente', 'Seguridad, salud y ambiente'), ('Servicios_generales', 'Servicios generales')], max_length=50)),
                ('Rcausa', models.CharField(choices=[('actualizacion', 'Actualizar datos'), ('no_reportado', 'No fue reportado'), ('mal_reportado', 'Mal reportado'), ('p_sindicales_atrasados', 'P. sindicales atrasados'), ('descuentos_atrasados', 'Descuentos atrasados'), ('valores_descuento_erroneos', 'Valores de descuento erróneos'), ('descuentos_jubilados', 'Descuentos de jubilados')], max_length=30)),
                ('Restado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta')], max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamo', to='myapp.usuario')),
            ],
        ),
    ]
