# Generated by Django 5.0 on 2024-01-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_reclamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='correo',
            field=models.CharField(blank=True, choices=[('arongarcia558@gmail.com', 'arongarcia558@gmail.com'), ('ggarciap3@unemi.edu.ec', 'ggarciap3@unemi.edu.ec')], max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='queja',
            name='correo',
            field=models.CharField(blank=True, choices=[('arongarcia558@gmail.com', 'arongarcia558@gmail.com'), ('ggarciap3@unemi.edu.ec', 'ggarciap3@unemi.edu.ec')], max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='correo',
            field=models.CharField(blank=True, choices=[('arongarcia558@gmail.com', 'arongarcia558@gmail.com'), ('ggarciap3@unemi.edu.ec', 'ggarciap3@unemi.edu.ec')], max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='correo',
            field=models.CharField(blank=True, choices=[('arongarcia558@gmail.com', 'arongarcia558@gmail.com'), ('ggarciap3@unemi.edu.ec', 'ggarciap3@unemi.edu.ec')], max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
