# Generated by Django 5.0 on 2024-01-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_peticion_correo_queja_correo_reclamo_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peticion',
            old_name='Pcausa',
            new_name='causa',
        ),
        migrations.RenameField(
            model_name='queja',
            old_name='Qcausa',
            new_name='causa',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='Rcausa',
            new_name='causa',
        ),
        migrations.RenameField(
            model_name='sugerencia',
            old_name='descripcion',
            new_name='causa',
        ),
    ]
