# Generated by Django 5.0 on 2024-01-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_pcausa_peticion_causa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peticion',
            old_name='Pestado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='Pfecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='Presponsable',
            new_name='responsable',
        ),
        migrations.RenameField(
            model_name='queja',
            old_name='Qestado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='queja',
            old_name='Qfecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='queja',
            old_name='Qresponsable',
            new_name='responsable',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='Restado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='Rfecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reclamo',
            old_name='Rresponsable',
            new_name='responsable',
        ),
    ]
