# Generated by Django 5.0 on 2024-01-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_pestado_peticion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='responsable',
            field=models.CharField(choices=[('Comunicacion_cultura', 'Comunicación clima y cultura'), ('Desarrollo_laboral', 'Desarrollo y relaciones laborales'), ('Nomina_compensaciones', 'Nomina y compensaciones'), ('Seguridad_salud_ambiente', 'Seguridad, salud y ambiente'), ('Servicios_generales', 'Servicios generales'), ('Campo', 'Campo'), ('Fabrica', 'Fabrica')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='myapp.usuario'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='myapp.usuario'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='responsable',
            field=models.CharField(choices=[('Comunicacion_cultura', 'Comunicación clima y cultura'), ('Desarrollo_laboral', 'Desarrollo y relaciones laborales'), ('Nomina_compensaciones', 'Nomina y compensaciones'), ('Seguridad_salud_ambiente', 'Seguridad, salud y ambiente'), ('Servicios_generales', 'Servicios generales'), ('Campo', 'Campo'), ('Fabrica', 'Fabrica')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='myapp.usuario'),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='myapp.usuario'),
        ),
    ]
