# Generated by Django 5.0 on 2024-01-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_peticion_estado_alter_peticion_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
