# Generated by Django 5.0 on 2024-01-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_peticion_doc_reclamo_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
