# Generated by Django 5.0 on 2024-01-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_queja_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticion',
            name='tipo_proceso',
            field=models.CharField(default='Peticion', max_length=20),
        ),
        migrations.AddField(
            model_name='queja',
            name='tipo_proceso',
            field=models.CharField(default='Queja', max_length=20),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='tipo_proceso',
            field=models.CharField(default='Reclamo', max_length=20),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='tipo_proceso',
            field=models.CharField(default='Sugerencia', max_length=20),
        ),
    ]
